2024-03-25 13:23:52.085 +03:00 [FTL] Run error
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Auth.Application.IAuthService Lifetime: Transient ImplementationType: Auth.Application.AuthService': Unable to resolve service for type 'Common.Application.Abstractions.Persistence.IRepository`1[Common.Domain.RefreshToken]' while attempting to activate 'Auth.Application.AuthService'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Auth.Application.IAuthService Lifetime: Transient ImplementationType: Auth.Application.AuthService': Unable to resolve service for type 'Common.Application.Abstractions.Persistence.IRepository`1[Common.Domain.RefreshToken]' while attempting to activate 'Auth.Application.AuthService'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Common.Application.Abstractions.Persistence.IRepository`1[Common.Domain.RefreshToken]' while attempting to activate 'Auth.Application.AuthService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in E:\Users\Aleks\C#\it_academia\ita-todo\Auth.Api\Program.cs:line 93
2024-03-25 13:26:57.236 +03:00 [ERR] Failed executing DbCommand (60ms) [Parameters=[@__Trim_0='?' (Size = 50)], CommandType='"Text"', CommandTimeout='30']
SELECT [t].[Id], [t].[Login], [t].[Password], [t].[RoleId], [t0].[ApplicationUserId], [t0].[ApplicationUserRoleId], [t0].[Id], [t0].[Name]
FROM (
    SELECT TOP(2) [a].[Id], [a].[Login], [a].[Password], [a].[RoleId]
    FROM [ApplicationUsers] AS [a]
    WHERE [a].[Login] = @__Trim_0
) AS [t]
LEFT JOIN (
    SELECT [a0].[ApplicationUserId], [a0].[ApplicationUserRoleId], [a1].[Id], [a1].[Name]
    FROM [ApplicationUserApplicationRole] AS [a0]
    INNER JOIN [ApplicationUserRoles] AS [a1] ON [a0].[ApplicationUserRoleId] = [a1].[Id]
) AS [t0] ON [t].[Id] = [t0].[ApplicationUserId]
ORDER BY [t].[Id], [t0].[ApplicationUserId], [t0].[ApplicationUserRoleId]
2024-03-25 13:26:57.271 +03:00 [ERR] An exception occurred while iterating over the results of a query for context type 'Common.Persistence.ApplicationDbContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Недопустимое имя объекта "ApplicationUsers".
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:4f717190-ce6f-4eb7-be9f-377bca73088a
Error Number:208,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Недопустимое имя объекта "ApplicationUsers".
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:4f717190-ce6f-4eb7-be9f-377bca73088a
Error Number:208,State:1,Class:16
